# Generated by Django 5.2.1 on 2026-05-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_pedido_bairro_pedido_cidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="enviar_talheres",
            field=models.BooleanField(default=True),
        ),
    ]
