# Generated by Django 5.2.1 on 2026-05-07 11:20

from decimal import Decimal

from django.db import migrations, models


def criar_faixas_iniciais(apps, schema_editor):
    FaixaFrete = apps.get_model("pedidos", "FaixaFrete")
    if FaixaFrete.objects.exists():
        return
    FaixaFrete.objects.bulk_create(
        [
            FaixaFrete(tipo="ate", km_limite=Decimal("5.00"), valor=Decimal("10.00"), ordem=10, ativo=True),
            FaixaFrete(tipo="ate", km_limite=Decimal("10.00"), valor=Decimal("20.00"), ordem=20, ativo=True),
            FaixaFrete(tipo="acima", km_limite=Decimal("10.00"), valor=Decimal("30.00"), ordem=30, ativo=True),
        ]
    )


def remover_faixas_iniciais(apps, schema_editor):
    FaixaFrete = apps.get_model("pedidos", "FaixaFrete")
    FaixaFrete.objects.filter(
        tipo__in=["ate", "acima"],
        km_limite__in=[Decimal("5.00"), Decimal("10.00")],
        valor__in=[Decimal("10.00"), Decimal("20.00"), Decimal("30.00")],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_pedido_enviar_talheres"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="distancia_km",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
        ),
        migrations.AddField(
            model_name="pedido",
            name="valor_frete",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
        ),
        migrations.CreateModel(
            name="FaixaFrete",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("ate", "Até"), ("acima", "Acima de")], default="ate", max_length=10)),
                ("km_limite", models.DecimalField(decimal_places=2, max_digits=6)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Faixa de frete",
                "verbose_name_plural": "Faixas de frete",
                "ordering": ["ordem", "km_limite", "id"],
            },
        ),
        migrations.RunPython(criar_faixas_iniciais, reverse_code=remover_faixas_iniciais),
    ]
