# Generated by Django 5.2.1 on 2026-05-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_faixafrete_pedido_distancia_km_pedido_valor_frete"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origem_endereco", models.CharField(blank=True, max_length=255)),
                (
                    "origem_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "origem_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuracao de entrega",
                "verbose_name_plural": "Configuracoes de entrega",
            },
        ),
        migrations.AlterField(
            model_name="faixafrete",
            name="tipo",
            field=models.CharField(
                choices=[("ate", "Ate"), ("acima", "Acima de")],
                default="ate",
                max_length=10,
            ),
        ),
    ]
