# Generated by Django 5.2.1 on 2026-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0011_configuracaoentrega_pix_chave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("pix", "Online Pix"),
                    ("dinheiro", "Dinheiro"),
                    ("cartao_entrega", "Cartao na entrega"),
                ],
                max_length=20,
            ),
        ),
    ]
