# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0033_alter_accessevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="checkout_key",
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
    ]
