# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0034_pedido_checkout_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="adicional",
            name="preco_ifood",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="bebida",
            name="preco_ifood",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="ifood",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prato",
            name="preco_ifood",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
