# Generated by Django 5.2.1 on 2026-07-25 18:25

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def criar_turnos_iniciais(apps, schema_editor):
    TurnoAtendimento = apps.get_model("pedidos", "TurnoAtendimento")
    Pedido = apps.get_model("pedidos", "Pedido")
    principal, _created = TurnoAtendimento.objects.get_or_create(
        codigo="principal",
        defaults={
            "nome": "Atendimento principal",
            "ativo": True,
            "dias_semana": "seg,ter,qua,qui,sex,sab,dom",
            "permite_entrega": True,
            "permite_retirada": True,
            "permite_promocao": True,
            "permite_cupom": True,
            "ordem": 10,
        },
    )
    TurnoAtendimento.objects.get_or_create(
        codigo="quentinha",
        defaults={
            "nome": "Quentinha",
            "ativo": False,
            "dias_semana": "seg,ter,qua,qui,sex,sab",
            "horario_inicio": datetime.time(18, 0),
            "horario_fim": datetime.time(20, 0),
            "horario_limite_entrega": datetime.time(19, 30),
            "permite_entrega": True,
            "permite_retirada": True,
            "modo_cardapio": "herdar_dia",
            "permite_promocao": False,
            "permite_cupom": False,
            "ordem": 20,
        },
    )
    Pedido.objects.filter(turno__isnull=True).update(turno=principal)


def remover_turnos_iniciais(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0053_datafechada"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisponibilidadeTurnoDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("pausado", models.BooleanField(default=False)),
                ("personalizado", models.BooleanField(default=False)),
                ("horario_inicio", models.TimeField(blank=True, null=True)),
                ("horario_fim", models.TimeField(blank=True, null=True)),
                ("horario_limite_entrega", models.TimeField(blank=True, null=True)),
                ("permite_entrega", models.BooleanField(blank=True, null=True)),
                ("permite_retirada", models.BooleanField(blank=True, null=True)),
                ("mensagem", models.CharField(blank=True, max_length=180)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Disponibilidade do turno",
                "verbose_name_plural": "Disponibilidades dos turnos",
                "ordering": ["-data", "turno__ordem", "turno__nome"],
            },
        ),
        migrations.CreateModel(
            name="TurnoAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("principal", "Atendimento principal"),
                            ("quentinha", "Quentinha"),
                        ],
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("ativo", models.BooleanField(default=False)),
                (
                    "dias_semana",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: seg,ter,qua,qui,sex,sab.",
                        max_length=40,
                    ),
                ),
                ("horario_inicio", models.TimeField(blank=True, null=True)),
                ("horario_fim", models.TimeField(blank=True, null=True)),
                ("horario_limite_entrega", models.TimeField(blank=True, null=True)),
                ("permite_entrega", models.BooleanField(default=True)),
                ("permite_retirada", models.BooleanField(default=True)),
                (
                    "modo_cardapio",
                    models.CharField(
                        choices=[
                            ("herdar_dia", "Herdar pratos do dia"),
                            ("fixo", "Usar pratos fixos"),
                        ],
                        default="herdar_dia",
                        max_length=20,
                    ),
                ),
                (
                    "preco_padrao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "desconto_padrao",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("permite_promocao", models.BooleanField(default=True)),
                ("permite_cupom", models.BooleanField(default=True)),
                ("mensagem", models.CharField(blank=True, max_length=180)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Turno de atendimento",
                "verbose_name_plural": "Turnos de atendimento",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="estoque_turno_liberado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedido",
            name="disponibilidade_turno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="pedidos.disponibilidadeturnodia",
            ),
        ),
        migrations.CreateModel(
            name="DisponibilidadeTurnoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preco", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "quantidade_disponivel",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("quantidade_reservada", models.PositiveIntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "disponibilidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pedidos.disponibilidadeturnodia",
                    ),
                ),
                (
                    "prato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disponibilidades_turno",
                        to="pedidos.prato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item disponivel no turno",
                "verbose_name_plural": "Itens disponiveis no turno",
                "ordering": ["ordem", "prato__nome"],
            },
        ),
        migrations.AddField(
            model_name="itempedido",
            name="disponibilidade_turno_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_pedido",
                to="pedidos.disponibilidadeturnoitem",
            ),
        ),
        migrations.AddField(
            model_name="disponibilidadeturnodia",
            name="turno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disponibilidades",
                to="pedidos.turnoatendimento",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="turno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="pedidos.turnoatendimento",
            ),
        ),
        migrations.CreateModel(
            name="TurnoPratoPadrao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "prato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnos_padrao",
                        to="pedidos.prato",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pratos_padrao",
                        to="pedidos.turnoatendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prato padrao do turno",
                "verbose_name_plural": "Pratos padrao do turno",
                "ordering": ["ordem", "prato__nome"],
            },
        ),
        migrations.AddConstraint(
            model_name="disponibilidadeturnoitem",
            constraint=models.UniqueConstraint(
                fields=("disponibilidade", "prato"),
                name="unique_disponibilidade_turno_prato",
            ),
        ),
        migrations.AddConstraint(
            model_name="disponibilidadeturnodia",
            constraint=models.UniqueConstraint(
                fields=("turno", "data"), name="unique_turno_disponibilidade_data"
            ),
        ),
        migrations.AddConstraint(
            model_name="turnopratopadrao",
            constraint=models.UniqueConstraint(
                fields=("turno", "prato"), name="unique_turno_prato_padrao"
            ),
        ),
        migrations.RunPython(criar_turnos_iniciais, remover_turnos_iniciais),
    ]
