# Generated by Django 5.2.1 on 2026-07-25 18:58

from django.db import migrations, models


def renomear_turno_para_prato_pronto(apps, schema_editor):
    TurnoAtendimento = apps.get_model("pedidos", "TurnoAtendimento")
    TurnoAtendimento.objects.filter(codigo="quentinha").update(
        codigo="prato_pronto",
        nome="Prato Pronto",
    )


def restaurar_nome_anterior(apps, schema_editor):
    TurnoAtendimento = apps.get_model("pedidos", "TurnoAtendimento")
    TurnoAtendimento.objects.filter(codigo="prato_pronto").update(
        codigo="quentinha",
        nome="Quentinha",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0054_disponibilidadeturnodia_turnoatendimento_and_more"),
    ]

    operations = [
        migrations.RunPython(
            renomear_turno_para_prato_pronto,
            restaurar_nome_anterior,
        ),
        migrations.AlterField(
            model_name="turnoatendimento",
            name="codigo",
            field=models.CharField(
                choices=[
                    ("principal", "Atendimento principal"),
                    ("prato_pronto", "Prato Pronto"),
                ],
                max_length=24,
                unique=True,
            ),
        ),
    ]
