# Generated by Django 5.2.1 on 2026-07-25 19:11

import datetime
from decimal import Decimal

from django.db import migrations, models


ORIENTACAO_PRATO_PRONTO = (
    "Marmitas seladas e refrigeradas · Feitas no dia · Aqueça em casa."
)


def alinhar_prato_pronto_ao_criativo(apps, schema_editor):
    TurnoAtendimento = apps.get_model("pedidos", "TurnoAtendimento")
    Pedido = apps.get_model("pedidos", "Pedido")
    turno = TurnoAtendimento.objects.filter(codigo="prato_pronto").first()
    if not turno:
        return

    update_fields = []
    if (
        turno.horario_inicio == datetime.time(18, 0)
        and turno.horario_fim == datetime.time(20, 0)
        and turno.horario_limite_entrega == datetime.time(19, 30)
    ):
        turno.horario_inicio = datetime.time(17, 0)
        turno.horario_fim = datetime.time(19, 0)
        turno.horario_limite_entrega = datetime.time(19, 0)
        update_fields.extend(
            ["horario_inicio", "horario_fim", "horario_limite_entrega"]
        )
    if turno.preco_padrao is None:
        turno.preco_padrao = Decimal("22.00")
        update_fields.append("preco_padrao")
    if not turno.mensagem:
        turno.mensagem = "Facilidade para sua janta."
        update_fields.append("mensagem")
    if not turno.orientacao_cliente:
        turno.orientacao_cliente = ORIENTACAO_PRATO_PRONTO
        update_fields.append("orientacao_cliente")
    if update_fields:
        turno.save(update_fields=update_fields)

    Pedido.objects.filter(
        turno=turno,
        orientacao_turno_snapshot="",
    ).update(orientacao_turno_snapshot=turno.orientacao_cliente)


def restaurar_padrao_anterior(apps, schema_editor):
    TurnoAtendimento = apps.get_model("pedidos", "TurnoAtendimento")
    turno = TurnoAtendimento.objects.filter(codigo="prato_pronto").first()
    if not turno:
        return
    if (
        turno.horario_inicio == datetime.time(17, 0)
        and turno.horario_fim == datetime.time(19, 0)
        and turno.horario_limite_entrega == datetime.time(19, 0)
    ):
        turno.horario_inicio = datetime.time(18, 0)
        turno.horario_fim = datetime.time(20, 0)
        turno.horario_limite_entrega = datetime.time(19, 30)
    if turno.preco_padrao == Decimal("22.00"):
        turno.preco_padrao = None
    if turno.mensagem == "Facilidade para sua janta.":
        turno.mensagem = ""
    turno.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0055_alter_turnoatendimento_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="orientacao_turno_snapshot",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="turnoatendimento",
            name="orientacao_cliente",
            field=models.CharField(blank=True, default="", max_length=220),
        ),
        migrations.RunPython(
            alinhar_prato_pronto_ao_criativo,
            restaurar_padrao_anterior,
        ),
    ]
