from django.urls import path

from . import views

app_name = "pedidos"

urlpatterns = [
    path("", views.cardapio, name="cardapio"),
    path("dashboard/api/order-heatmap/", views.api_order_heatmap, name="api_order_heatmap"),
    path("dashboard/api/bairros-rio-verde/", views.api_bairros_rio_verde, name="api_bairros_rio_verde"),
    path("dashboard/api/bairros-polygons/", views.api_bairros_polygons, name="api_bairros_polygons"),
    path("api/address/delivery-time/", views.api_address_delivery_time, name="api_address_delivery_time"),
    path("api/cupom/validar/", views.api_validar_cupom, name="api_validar_cupom"),
    path("api/lista-impressao/", views.api_lista_impressao, name="api_lista_impressao"),
    path("api/pedidos/", views.api_pedidos, name="api_pedidos"),
    path("api/pedidos/token/<str:public_token>/", views.api_pedido_detalhe_token, name="api_pedido_detalhe_token"),
    path("api/pedidos/<int:pedido_id>/", views.api_pedido_detalhe, name="api_pedido_detalhe"),
    path("carrinho/", views.carrinho, name="carrinho"),
    path("checkout/", views.checkout, name="checkout"),
    path("pedido/criar/", views.criar_pedido, name="criar_pedido"),
    path("pedido/retirada/", views.criar_retirada, name="criar_retirada"),
    path("pedido/<str:public_token>/sucesso/", views.sucesso, name="sucesso"),
    path("meus-pedidos/", views.meus_pedidos, name="meus_pedidos"),
    path("api/meus-pedidos/", views.api_meus_pedidos, name="api_meus_pedidos"),
    path("pedido/<str:public_token>/acompanhar/", views.acompanhar_pedido, name="acompanhar_pedido"),
    path("controle/", views.cozinha, name="cozinha"),
    path("controle/operacao/", views.cozinha_pedidos, name="cozinha_operacao"),
    path("controle/pedidos/", views.pedidos_admin, name="cozinha_pedidos"),
    path("controle/pedidos-aprovacao/", views.pedidos_aprovacao_admin, name="pedidos_aprovacao_admin"),
    path("controle/pedidos-concluidos/", views.pedidos_concluidos_admin, name="pedidos_concluidos_admin"),
    path("controle/pedidos/<int:pedido_id>/", views.pedido_detalhe_admin, name="pedido_detalhe_admin"),
    path("controle/clientes/", views.clientes_admin, name="clientes_admin"),
    path("controle/clientes/<int:cliente_id>/", views.cliente_detalhe_admin, name="cliente_detalhe_admin"),
    path("controle/clientes/conflitos/", views.clientes_conflitos_admin, name="clientes_conflitos_admin"),
    path("controle/ajustes/", views.ajustes_admin, name="ajustes_admin"),
    path("controle/pratos/", views.gestao_pratos, name="gestao_pratos"),
    path("controle/bebidas/", views.gestao_bebidas, name="gestao_bebidas"),
    path("controle/adicionais/", views.adicionais_admin, name="adicionais_admin"),
    path("controle/outros/", views.outros_admin, name="outros_admin"),
    path("controle/cupons/", views.cupons_admin, name="cupons_admin"),
    path("controle/pratos/salvar/", views.salvar_prato, name="salvar_prato"),
    path("controle/pratos/<int:prato_id>/alternar/", views.alternar_prato, name="alternar_prato"),
    path("controle/pratos/<int:prato_id>/imagem/excluir/", views.excluir_imagem_prato, name="excluir_imagem_prato"),
    path("controle/bebidas/salvar/", views.salvar_bebida, name="salvar_bebida"),
    path("controle/bebidas/<int:bebida_id>/alternar/", views.alternar_bebida, name="alternar_bebida"),
    path("controle/bebidas/<int:bebida_id>/imagem/excluir/", views.excluir_imagem_bebida, name="excluir_imagem_bebida"),
    path("controle/adicionais/salvar/", views.salvar_adicional, name="salvar_adicional"),
    path("controle/adicionais/<int:adicional_id>/alternar/", views.alternar_adicional, name="alternar_adicional"),
    path("controle/adicionais/<int:adicional_id>/imagem/excluir/", views.excluir_imagem_adicional, name="excluir_imagem_adicional"),
    path("controle/api/pedidos/", views.api_pedidos_cozinha, name="api_pedidos_cozinha"),
    path("controle/api/pedidos-admin/", views.api_pedidos_admin, name="api_pedidos_admin"),
    path("controle/api/pedidos-aprovacao/", views.api_pedidos_aprovacao_admin, name="api_pedidos_aprovacao_admin"),
    path("controle/api/pedidos-concluidos/", views.api_pedidos_concluidos_admin, name="api_pedidos_concluidos_admin"),
    path("controle/api/pedido/<int:pedido_id>/copias/", views.api_pedido_copias, name="api_pedido_copias"),
    path("controle/api/pedido/<int:pedido_id>/lista-impressao/", views.registrar_pedido_lista_impressao, name="registrar_pedido_lista_impressao"),
    path("controle/api/catalogo-editor/", views.api_catalogo_editor_pedido, name="api_catalogo_editor_pedido"),
    path("controle/api/operacao/", views.api_cozinha_operacao, name="api_cozinha_operacao"),
    path("controle/pedidos/novo/", views.pedido_novo_admin, name="pedido_novo_admin"),
    path("controle/pedido/<int:pedido_id>/finalizar-novo/", views.finalizar_pedido_novo_admin, name="finalizar_pedido_novo_admin"),
    path("controle/pedido/<int:pedido_id>/status/", views.atualizar_status_pedido, name="atualizar_status_pedido"),
    path("controle/pedido/<int:pedido_id>/entregador/", views.alternar_entregador_pedido, name="alternar_entregador_pedido"),
    path("controle/pedido/<int:pedido_id>/pagamento/", views.atualizar_pagamento_pedido, name="atualizar_pagamento_pedido"),
    path("controle/pedido/<int:pedido_id>/cupom/", views.atualizar_cupom_pedido, name="atualizar_cupom_pedido"),
    path("controle/pedido/<int:pedido_id>/itens/", views.atualizar_itens_pedido, name="atualizar_itens_pedido"),
    path("controle/pedido/<int:pedido_id>/dados/", views.atualizar_dados_pedido, name="atualizar_dados_pedido"),
    path("controle/pedido/<int:pedido_id>/entrega/", views.atualizar_entrega_pedido, name="atualizar_entrega_pedido"),
]
